container:
  dockerfile: ci/cirrus.Dockerfile

env:
  EMAIL: cirrus@cirrus-ci.org

device_matrix_template: &DEVICE_MATRIX_TEMPLATE
  - env:
      DEVICE: --trezor-1
    depends_on:
      - Trezor 1 Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Trezor 1 Sim Builder/sim/trezor-firmware.tar.gz"
      - tar -xvf "trezor-firmware.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"
  - env:
      DEVICE: --trezor-t
    depends_on:
      - Trezor T Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Trezor T Sim Builder/sim/trezor-firmware.tar.gz"
      - tar -xvf "trezor-firmware.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"
  - env:
      DEVICE: --coldcard
    depends_on:
      - Coldcard Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Coldcard Sim Builder/sim/coldcard-mpy.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"
    sim_install_script:
      - pushd test/work; git clone --recursive https://github.com/Coldcard/firmware.git; popd
      - tar -xvf "coldcard-mpy.tar.gz"
      - pushd test/work/firmware; git am ../../data/coldcard-multisig.patch; popd
      - poetry run pip install -r test/work/firmware/requirements.txt
      - pip install -r test/work/firmware/requirements.txt
  - env:
      DEVICE: --bitbox01
    depends_on:
      - Bitbox01 Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Bitbox01 Sim Builder/sim/mcu.tar.gz"
      - tar -xvf "mcu.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"
  - env:
      DEVICE: --ledger
    depends_on:
      - Ledger Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Ledger Sim Builder/sim/speculos.tar.gz"
      - tar -xvf "speculos.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"
    sim_install_script:
      - poetry run pip install construct flask-restful jsonschema mnemonic pyelftools pillow requests
      - pip install construct flask-restful jsonschema mnemonic pyelftools pillow requests
  - env:
      DEVICE: --keepkey
    depends_on:
      - Keepkey Sim Builder
      - dist_builder
      - bitcoind_builder
    fetch_sim_script:
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/Keepkey Sim Builder/sim/keepkey-firmware.tar.gz"
      - tar -xvf "keepkey-firmware.tar.gz"
      - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/bitcoind_builder/bitcoin/bitcoin.tar.gz"
      - tar -xvf "bitcoin.tar.gz"

lint_task:
  test_script:
    - flake8

task:
  install_script:
    - poetry install
  matrix:
    - name: Type Check
      type_check_script: >
        poetry run
        mypy
        hwi.py
        hwilib/_base58.py
        hwilib/_bech32.py
        hwilib/_cli.py
        hwilib/commands.py
        hwilib/common.py
        hwilib/descriptor.py
        hwilib/devices/bitbox02.py
        hwilib/devices/coldcard.py
        hwilib/devices/digitalbitbox.py
        hwilib/devices/__init__.py
        hwilib/devices/keepkey.py
        hwilib/devices/ledger.py
        hwilib/devices/trezor.py
        hwilib/errors.py
        hwilib/_script.py
        hwilib/_serialize.py
        hwilib/tx.py
        hwilib/hwwclient.py
        hwilib/__init__.py
        hwilib/key.py
        hwilib/udevinstaller.py
    - name: Non-Device Tests
      test_script: cd test; poetry run ./run_tests.py; cd ..

wine_builder_task:
  container:
    dockerfile: contrib/build.Dockerfile
  build_script:
    - contrib/build_wine.sh
    - find dist -type f -exec sha256sum {} \;

bitcoind_builder_task:
  bitcoind_cache:
    folder: test/work/bitcoin
  ccache_cache:
    folder: /root/.ccache
  env:
    BUILD_BITCOIND: 1
  build_script:
    - cd test; ./setup_environment.sh --bitcoind; cd ..
    - tar -czf bitcoin.tar.gz test/work/bitcoin
  bitcoin_artifacts:
    path: "bitcoin.tar.gz"

task:
  env:
    DEVICE: --trezor-1
  name: Trezor 1 Sim Builder
  sim_work_cache:
    folder: test/work/trezor-firmware
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf trezor-firmware.tar.gz test/work/trezor-firmware
  sim_artifacts:
    path: "trezor-firmware.tar.gz"

task:
  env:
    DEVICE: --trezor-t
  name: Trezor T Sim Builder
  sim_work_cache:
    folder: test/work/trezor-firmware
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf trezor-firmware.tar.gz test/work/trezor-firmware
  sim_artifacts:
    path: "trezor-firmware.tar.gz"

task:
  env:
    DEVICE: --coldcard
  name: Coldcard Sim Builder
  sim_work_cache:
    folder: test/work/firmware
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf coldcard-mpy.tar.gz test/work/firmware/external/micropython/ports/unix/coldcard-mpy test/work/firmware/unix/coldcard-mpy test/work/firmware/unix/l-mpy test/work/firmware/unix/l-port
  sim_artifacts:
    path: "coldcard-mpy.tar.gz"

task:
  env:
    DEVICE: --bitbox01
  name: Bitbox01 Sim Builder
  sim_work_cache:
    folder: test/work/mcu
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf mcu.tar.gz test/work/mcu
  sim_artifacts:
    path: "mcu.tar.gz"

task:
  env:
    DEVICE: --ledger
  name: Ledger Sim Builder
  sim_work_cache:
    folder: test/work/speculos
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf speculos.tar.gz test/work/speculos
  sim_artifacts:
    path: "speculos.tar.gz"

task:
  env:
    DEVICE: --keepkey
  name: Keepkey Sim Builder
  sim_work_cache:
    folder: test/work/keepkey-firmware
  build_script:
    - cd test; ./setup_environment.sh $DEVICE; cd ..
    - tar -czf keepkey-firmware.tar.gz test/work/keepkey-firmware/bin
  sim_artifacts:
    path: "keepkey-firmware.tar.gz"


dist_builder_task:
  container:
    dockerfile: contrib/build.Dockerfile
  build_script:
    - contrib/build_bin.sh
    - contrib/build_dist.sh
    - find dist -type f -exec sha256sum {} \;
  built_dist_artifacts:
    path: "dist/*"

task:
  matrix:
    << : *DEVICE_MATRIX_TEMPLATE
  fetch_dist_script:
    - wget -nv "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_BUILD_ID/dist_builder/built_dist.zip"
    - unzip built_dist.zip
  matrix:
    - name: $DEVICE Wheel
      install_script: pip install dist/*.whl
      test_script: cd test; ./run_tests.py $DEVICE --interface=cli --device-only; cd ..
    - name: $DEVICE Sdist
      install_script: pip install $(find dist -name "*.tar.gz" -a -not -name "*amd64*")
      test_script: cd test; ./run_tests.py $DEVICE --interface=cli --device-only; cd ..
    - name: $DEVICE Bindist
      install_script: poetry install
      untar_bindist_script: cd dist; tar -xvf hwi*linux*.tar.gz; cd ..
      test_script: cd test; poetry run ./run_tests.py $DEVICE --interface=bindist --device-only; cd ..
  on_failure:
    failed_script: tail -v -n +1 test/*.std*

task:
  matrix:
    - container:
        dockerfile: ci/cirrus.Dockerfile
      env:
        PYTHON: 3.6
    - container:
        dockerfile: ci/py37.Dockerfile
      env:
        PYTHON: 3.7
    - container:
        dockerfile: ci/py38.Dockerfile
      env:
        PYTHON: 3.8
    - container:
        dockerfile: ci/py39.Dockerfile
      env:
        PYTHON: 3.9
    - container:
        dockerfile: ci/py310.Dockerfile
      env:
        PYTHON: 3.10
  matrix:
    << : *DEVICE_MATRIX_TEMPLATE
  matrix:
    - env:
        INTERFACE: library
    - env:
        INTERFACE: cli
    - env:
        INTERFACE: stdin
  name: Python $PYTHON $DEVICE $INTERFACE
  install_script: poetry install
  test_script: cd test; poetry run ./run_tests.py $DEVICE --interface=$INTERFACE --device-only; cd ..
  on_failure:
    failed_script: tail -v -n +1 test/*.std*
