[project]
name = "hwi"
version = "3.2.0"
description = "A library for working with Bitcoin hardware wallets"
authors = [{ name = "Ava Chow", email = "<me@achow101.com>" }]
license = "MIT"
readme = "README.md"

requires-python = ">=3.10,<3.16"
dependencies = [
    "hidapi>=0.14.0",
    "ecdsa>=0",
    "pyaes>=1.6,<2.0",
    "mnemonic>=0",
    "typing-extensions>=4.4,<5.0",
    "libusb1>=1.7,<4",
    "cbor2>=5.9.0,<6.0.0",
    "pyserial>=3.5,<4.0",
    "semver>=3.0.1,<4.0",
    "noiseprotocol>=0.3.1,<0.4.0",
    "protobuf>=4.23.3",
]

[project.optional-dependencies]
qt = [
    "pyside2 (>=5.15.2.1,<6.0) ; python_version < '3.11'",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.3,<7.0",
    "autopep8>=1",
    "flake8>=3",
    "mypy>=0",
    "sphinx>=4",
    "sphinx-rtd-theme>=1",
    "sphinxcontrib-autoprogram>=0",
]

[project.urls]
repository = "https://github.com/bitcoin-core/HWI"
homepage = "https://github.com/bitcoin-core/HWI"

[project.scripts]
hwi = 'hwilib._cli:main'

[project.gui-scripts]
hwi-qt = 'hwilib._gui:main'

[tool.poetry]
exclude = ["docs/", "test/"]
include = ["hwilib/**/*.py", "udev/", "hwilib/py.typed"]
packages = [
    { include = "hwi.py" },
    { include = "hwi-qt.py" },
    { include = "hwilib" },
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
