# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

btc_transaction_begin = 160  # type: Literal[160]
btc_transaction_update_script = 161  # type: Literal[161]
btc_transaction_update_prevtx = 162  # type: Literal[162]
btc_transaction_finish = 163  # type: Literal[163]
btc_transaction_retrieve = 164  # type: Literal[164]
btc_get_address = 176  # type: Literal[176]
btc_transaction_begin_zc = 192  # type: Literal[192]
btc_message_sign = 208  # type: Literal[208]
btc_message_update = 209  # type: Literal[209]
btc_message_sign_finish = 210  # type: Literal[210]
