# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coin.proto',
  package='coin',
  syntax='proto2',
  serialized_pb=_b('\n\ncoin.proto\x12\x04\x63oin\x1a\x0cnanopb.proto\"\xe0\x01\n!sync_account_info_req_parameter_t\x12\x11\n\ttotal_num\x18\x01 \x02(\r\x12\x13\n\x0b\x61\x63\x63ount_idx\x18\x02 \x02(\r\x12\x13\n\x04\x64\x61te\x18\x03 \x02(\tB\x05\x92?\x02\x08\x11\x12\x19\n\ncoin_group\x18\x04 \x02(\tB\x05\x92?\x02\x08\x10\x12\x18\n\tcoin_name\x18\x05 \x02(\tB\x05\x92?\x02\x08\x10\x12\x14\n\x05label\x18\x06 \x02(\tB\x05\x92?\x02\x08\x0f\x12\x16\n\x07\x62\x61lance\x18\x07 \x02(\tB\x05\x92?\x02\x08\x0f\x12\x1b\n\x0c\x61\x64\x64ress_path\x18\x08 \x02(\tB\x05\x92?\x02\x08\x19\"\xb2\x01\n get_account_info_res_parameter_t\x12\x11\n\ttotal_num\x18\x01 \x02(\r\x12\x13\n\x0b\x61\x63\x63ount_idx\x18\x02 \x02(\r\x12\x18\n\tcoin_name\x18\x03 \x02(\tB\x05\x92?\x02\x08\x10\x12\x14\n\x05label\x18\x04 \x02(\tB\x05\x92?\x02\x08\x0f\x12\x1b\n\x0c\x61\x64\x64ress_path\x18\x06 \x02(\tB\x05\x92?\x02\x08\x19\x12\x19\n\ncoin_group\x18\x07 \x01(\tB\x05\x92?\x02\x08\x10\"S\n\x1e\x65xtract_pubkey_req_parameter_t\x12\x18\n\tbip32name\x18\x01 \x02(\tB\x05\x92?\x02\x08\x11\x12\x17\n\x08key_path\x18\x02 \x02(\tB\x05\x92?\x02\x08\x33\"7\n\x1e\x65xtract_pubkey_res_parameter_t\x12\x15\n\x06pubkey\x18\x01 \x02(\x0c\x42\x05\x92?\x02\x08yB#\n\x1b\x63om.iotrust.dcent.wam.protoB\x04\x43oin')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T = _descriptor.Descriptor(
  name='sync_account_info_req_parameter_t',
  full_name='coin.sync_account_info_req_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_num', full_name='coin.sync_account_info_req_parameter_t.total_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_idx', full_name='coin.sync_account_info_req_parameter_t.account_idx', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='coin.sync_account_info_req_parameter_t.date', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\021')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_group', full_name='coin.sync_account_info_req_parameter_t.coin_group', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='coin.sync_account_info_req_parameter_t.coin_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='coin.sync_account_info_req_parameter_t.label', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='coin.sync_account_info_req_parameter_t.balance', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_path', full_name='coin.sync_account_info_req_parameter_t.address_path', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\031')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=259,
)


_GET_ACCOUNT_INFO_RES_PARAMETER_T = _descriptor.Descriptor(
  name='get_account_info_res_parameter_t',
  full_name='coin.get_account_info_res_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_num', full_name='coin.get_account_info_res_parameter_t.total_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_idx', full_name='coin.get_account_info_res_parameter_t.account_idx', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='coin.get_account_info_res_parameter_t.coin_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='coin.get_account_info_res_parameter_t.label', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_path', full_name='coin.get_account_info_res_parameter_t.address_path', index=4,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\031')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_group', full_name='coin.get_account_info_res_parameter_t.coin_group', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=440,
)


_EXTRACT_PUBKEY_REQ_PARAMETER_T = _descriptor.Descriptor(
  name='extract_pubkey_req_parameter_t',
  full_name='coin.extract_pubkey_req_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bip32name', full_name='coin.extract_pubkey_req_parameter_t.bip32name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\021')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_path', full_name='coin.extract_pubkey_req_parameter_t.key_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\0103')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=525,
)


_EXTRACT_PUBKEY_RES_PARAMETER_T = _descriptor.Descriptor(
  name='extract_pubkey_res_parameter_t',
  full_name='coin.extract_pubkey_res_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='coin.extract_pubkey_res_parameter_t.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010y')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=582,
)

DESCRIPTOR.message_types_by_name['sync_account_info_req_parameter_t'] = _SYNC_ACCOUNT_INFO_REQ_PARAMETER_T
DESCRIPTOR.message_types_by_name['get_account_info_res_parameter_t'] = _GET_ACCOUNT_INFO_RES_PARAMETER_T
DESCRIPTOR.message_types_by_name['extract_pubkey_req_parameter_t'] = _EXTRACT_PUBKEY_REQ_PARAMETER_T
DESCRIPTOR.message_types_by_name['extract_pubkey_res_parameter_t'] = _EXTRACT_PUBKEY_RES_PARAMETER_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sync_account_info_req_parameter_t = _reflection.GeneratedProtocolMessageType('sync_account_info_req_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _SYNC_ACCOUNT_INFO_REQ_PARAMETER_T,
  __module__ = 'coin_pb2'
  # @@protoc_insertion_point(class_scope:coin.sync_account_info_req_parameter_t)
  ))
_sym_db.RegisterMessage(sync_account_info_req_parameter_t)

get_account_info_res_parameter_t = _reflection.GeneratedProtocolMessageType('get_account_info_res_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _GET_ACCOUNT_INFO_RES_PARAMETER_T,
  __module__ = 'coin_pb2'
  # @@protoc_insertion_point(class_scope:coin.get_account_info_res_parameter_t)
  ))
_sym_db.RegisterMessage(get_account_info_res_parameter_t)

extract_pubkey_req_parameter_t = _reflection.GeneratedProtocolMessageType('extract_pubkey_req_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACT_PUBKEY_REQ_PARAMETER_T,
  __module__ = 'coin_pb2'
  # @@protoc_insertion_point(class_scope:coin.extract_pubkey_req_parameter_t)
  ))
_sym_db.RegisterMessage(extract_pubkey_req_parameter_t)

extract_pubkey_res_parameter_t = _reflection.GeneratedProtocolMessageType('extract_pubkey_res_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACT_PUBKEY_RES_PARAMETER_T,
  __module__ = 'coin_pb2'
  # @@protoc_insertion_point(class_scope:coin.extract_pubkey_res_parameter_t)
  ))
_sym_db.RegisterMessage(extract_pubkey_res_parameter_t)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033com.iotrust.dcent.wam.protoB\004Coin'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['date'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['date']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\021'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['coin_group'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['coin_group']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['coin_name'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['coin_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['label'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['label']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['balance'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['balance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017'))
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['address_path'].has_options = True
_SYNC_ACCOUNT_INFO_REQ_PARAMETER_T.fields_by_name['address_path']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\031'))
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['coin_name'].has_options = True
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['coin_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020'))
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['label'].has_options = True
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['label']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\017'))
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['address_path'].has_options = True
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['address_path']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\031'))
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['coin_group'].has_options = True
_GET_ACCOUNT_INFO_RES_PARAMETER_T.fields_by_name['coin_group']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020'))
_EXTRACT_PUBKEY_REQ_PARAMETER_T.fields_by_name['bip32name'].has_options = True
_EXTRACT_PUBKEY_REQ_PARAMETER_T.fields_by_name['bip32name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\021'))
_EXTRACT_PUBKEY_REQ_PARAMETER_T.fields_by_name['key_path'].has_options = True
_EXTRACT_PUBKEY_REQ_PARAMETER_T.fields_by_name['key_path']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\0103'))
_EXTRACT_PUBKEY_RES_PARAMETER_T.fields_by_name['pubkey'].has_options = True
_EXTRACT_PUBKEY_RES_PARAMETER_T.fields_by_name['pubkey']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010y'))
# @@protoc_insertion_point(module_scope)
