# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

sync_account_info = 176  # type: Literal[176]
get_account_info = 177  # type: Literal[177]
extract_pubkey = 178  # type: Literal[178]
