# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class coin_list_t(p.MessageType):

    def __init__(
        self,
        name: str = None,
    ) -> None:
        self.name = name

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('name', p.UnicodeType, 0),  # required
        }
