# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class command_t(p.MessageType):

    def __init__(
        self,
        value: int = None,
    ) -> None:
        self.value = value

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('value', p.UVarintType, 0),  # required
        }
