# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

get_info = 160  # type: Literal[160]
set_label = 162  # type: Literal[162]
init_wallet = 208  # type: Literal[208]
reboot_to_bl = 224  # type: Literal[224]
send_dummy_cmd = 176  # type: Literal[176]
