# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='device.proto',
  package='device',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\x1a\x0cnanopb.proto\"\xf2\x01\n\x18get_info_res_parameter_t\x12\x14\n\x05\x64\x65vid\x18\x01 \x02(\tB\x05\x92?\x02\x08\x41\x12\x15\n\x06\x66w_ver\x18\x02 \x02(\tB\x05\x92?\x02\x08\x0e\x12\x16\n\x07ksm_ver\x18\x03 \x02(\tB\x05\x92?\x02\x08\x0e\x12%\n\x05state\x18\x04 \x02(\x0e\x32\x16.device.wallet_state_t\x12(\n\x04\x63oin\x18\x05 \x03(\x0b\x32\x13.device.coin_list_tB\x05\x92?\x02\x10,\x12*\n\x0b\x66ingerprint\x18\x06 \x02(\x0b\x32\x15.device.fingerprint_t\x12\x14\n\x05label\x18\x07 \x02(\tB\x05\x92?\x02\x08\x0b\"1\n\x19set_label_req_parameter_t\x12\x14\n\x05label\x18\x01 \x02(\tB\x05\x92?\x02\x08\x0b\";\n\x1binit_wallet_req_parameter_t\x12\x1c\n\x08mnemonic\x18\x02 \x03(\tB\n\x92?\x02\x08\x14\x92?\x02\x10\x18\"2\n\rfingerprint_t\x12\x0f\n\x07max_num\x18\x01 \x02(\r\x12\x10\n\x08\x65nrolled\x18\x02 \x02(\r\"\"\n\x0b\x63oin_list_t\x12\x13\n\x04name\x18\x01 \x02(\tB\x05\x92?\x02\x08\x10*^\n\x0ewallet_state_t\x12\x08\n\x04init\x10\x00\x12\t\n\x05ready\x10\x01\x12\n\n\x06secure\x10\x02\x12\r\n\tlocked_fp\x10\x03\x12\x0e\n\nlocked_pin\x10\x04\x12\x0c\n\x07invalid\x10\xff\x01\x42%\n\x1b\x63om.iotrust.dcent.wam.protoB\x06\x44\x65vice')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_WALLET_STATE_T = _descriptor.EnumDescriptor(
  name='wallet_state_t',
  full_name='device.wallet_state_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='init', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ready', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='secure', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='locked_fp', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='locked_pin', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='invalid', index=5, number=255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=483,
  serialized_end=577,
)
_sym_db.RegisterEnumDescriptor(_WALLET_STATE_T)

wallet_state_t = enum_type_wrapper.EnumTypeWrapper(_WALLET_STATE_T)
init = 0
ready = 1
secure = 2
locked_fp = 3
locked_pin = 4
invalid = 255



_GET_INFO_RES_PARAMETER_T = _descriptor.Descriptor(
  name='get_info_res_parameter_t',
  full_name='device.get_info_res_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devid', full_name='device.get_info_res_parameter_t.devid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010A')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_ver', full_name='device.get_info_res_parameter_t.fw_ver', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\016')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ksm_ver', full_name='device.get_info_res_parameter_t.ksm_ver', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\016')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='device.get_info_res_parameter_t.state', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin', full_name='device.get_info_res_parameter_t.coin', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020,')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='device.get_info_res_parameter_t.fingerprint', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='device.get_info_res_parameter_t.label', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\013')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=281,
)


_SET_LABEL_REQ_PARAMETER_T = _descriptor.Descriptor(
  name='set_label_req_parameter_t',
  full_name='device.set_label_req_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='device.set_label_req_parameter_t.label', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\013')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=332,
)


_INIT_WALLET_REQ_PARAMETER_T = _descriptor.Descriptor(
  name='init_wallet_req_parameter_t',
  full_name='device.init_wallet_req_parameter_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mnemonic', full_name='device.init_wallet_req_parameter_t.mnemonic', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\024\222?\002\020\030')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=393,
)


_FINGERPRINT_T = _descriptor.Descriptor(
  name='fingerprint_t',
  full_name='device.fingerprint_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_num', full_name='device.fingerprint_t.max_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enrolled', full_name='device.fingerprint_t.enrolled', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=445,
)


_COIN_LIST_T = _descriptor.Descriptor(
  name='coin_list_t',
  full_name='device.coin_list_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='device.coin_list_t.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=481,
)

_GET_INFO_RES_PARAMETER_T.fields_by_name['state'].enum_type = _WALLET_STATE_T
_GET_INFO_RES_PARAMETER_T.fields_by_name['coin'].message_type = _COIN_LIST_T
_GET_INFO_RES_PARAMETER_T.fields_by_name['fingerprint'].message_type = _FINGERPRINT_T
DESCRIPTOR.message_types_by_name['get_info_res_parameter_t'] = _GET_INFO_RES_PARAMETER_T
DESCRIPTOR.message_types_by_name['set_label_req_parameter_t'] = _SET_LABEL_REQ_PARAMETER_T
DESCRIPTOR.message_types_by_name['init_wallet_req_parameter_t'] = _INIT_WALLET_REQ_PARAMETER_T
DESCRIPTOR.message_types_by_name['fingerprint_t'] = _FINGERPRINT_T
DESCRIPTOR.message_types_by_name['coin_list_t'] = _COIN_LIST_T
DESCRIPTOR.enum_types_by_name['wallet_state_t'] = _WALLET_STATE_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

get_info_res_parameter_t = _reflection.GeneratedProtocolMessageType('get_info_res_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _GET_INFO_RES_PARAMETER_T,
  __module__ = 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.get_info_res_parameter_t)
  ))
_sym_db.RegisterMessage(get_info_res_parameter_t)

set_label_req_parameter_t = _reflection.GeneratedProtocolMessageType('set_label_req_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _SET_LABEL_REQ_PARAMETER_T,
  __module__ = 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.set_label_req_parameter_t)
  ))
_sym_db.RegisterMessage(set_label_req_parameter_t)

init_wallet_req_parameter_t = _reflection.GeneratedProtocolMessageType('init_wallet_req_parameter_t', (_message.Message,), dict(
  DESCRIPTOR = _INIT_WALLET_REQ_PARAMETER_T,
  __module__ = 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.init_wallet_req_parameter_t)
  ))
_sym_db.RegisterMessage(init_wallet_req_parameter_t)

fingerprint_t = _reflection.GeneratedProtocolMessageType('fingerprint_t', (_message.Message,), dict(
  DESCRIPTOR = _FINGERPRINT_T,
  __module__ = 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.fingerprint_t)
  ))
_sym_db.RegisterMessage(fingerprint_t)

coin_list_t = _reflection.GeneratedProtocolMessageType('coin_list_t', (_message.Message,), dict(
  DESCRIPTOR = _COIN_LIST_T,
  __module__ = 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.coin_list_t)
  ))
_sym_db.RegisterMessage(coin_list_t)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033com.iotrust.dcent.wam.protoB\006Device'))
_GET_INFO_RES_PARAMETER_T.fields_by_name['devid'].has_options = True
_GET_INFO_RES_PARAMETER_T.fields_by_name['devid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010A'))
_GET_INFO_RES_PARAMETER_T.fields_by_name['fw_ver'].has_options = True
_GET_INFO_RES_PARAMETER_T.fields_by_name['fw_ver']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\016'))
_GET_INFO_RES_PARAMETER_T.fields_by_name['ksm_ver'].has_options = True
_GET_INFO_RES_PARAMETER_T.fields_by_name['ksm_ver']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\016'))
_GET_INFO_RES_PARAMETER_T.fields_by_name['coin'].has_options = True
_GET_INFO_RES_PARAMETER_T.fields_by_name['coin']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020,'))
_GET_INFO_RES_PARAMETER_T.fields_by_name['label'].has_options = True
_GET_INFO_RES_PARAMETER_T.fields_by_name['label']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\013'))
_SET_LABEL_REQ_PARAMETER_T.fields_by_name['label'].has_options = True
_SET_LABEL_REQ_PARAMETER_T.fields_by_name['label']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\013'))
_INIT_WALLET_REQ_PARAMETER_T.fields_by_name['mnemonic'].has_options = True
_INIT_WALLET_REQ_PARAMETER_T.fields_by_name['mnemonic']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\024\222?\002\020\030'))
_COIN_LIST_T.fields_by_name['name'].has_options = True
_COIN_LIST_T.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\010\020'))
# @@protoc_insertion_point(module_scope)
