# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

none = 0  # type: Literal[0]
invalid_access = 1  # type: Literal[1]
internal_process = 2  # type: Literal[2]
memory_access = 3  # type: Literal[3]
invalid_format = 4  # type: Literal[4]
not_support = 5  # type: Literal[5]
invalid_command = 6  # type: Literal[6]
wrong_length = 7  # type: Literal[7]
wrong_number = 8  # type: Literal[8]
lowlevel_protocol = 65532  # type: Literal[65532]
user_cancel = 65533  # type: Literal[65533]
device_busy = 65534  # type: Literal[65534]
unknown = 65535  # type: Literal[65535]
