# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class extract_pubkey_req_parameter_t(p.MessageType):

    def __init__(
        self,
        bip32name: str = None,
        key_path: str = None,
    ) -> None:
        self.bip32name = bip32name
        self.key_path = key_path

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('bip32name', p.UnicodeType, 0),  # required
            2: ('key_path', p.UnicodeType, 0),  # required
        }
