# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class fingerprint_t(p.MessageType):

    def __init__(
        self,
        max_num: int = None,
        enrolled: int = None,
    ) -> None:
        self.max_num = max_num
        self.enrolled = enrolled

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('max_num', p.UVarintType, 0),  # required
            2: ('enrolled', p.UVarintType, 0),  # required
        }
