# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class get_address_req_parameter_t(p.MessageType):

    def __init__(
        self,
        key_path: str = None,
    ) -> None:
        self.key_path = key_path

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            2: ('key_path', p.UnicodeType, 0),  # required
        }
