# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

from .command_t import command_t

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class req_body_t(p.MessageType):

    def __init__(
        self,
        command: command_t = None,
        parameter: bytes = None,
    ) -> None:
        self.command = command
        self.parameter = parameter

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('command', command_t, 0),  # required
            2: ('parameter', p.BytesType, 0),
        }
