# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

from .req_body_t import req_body_t
from .req_header_t import req_header_t

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class request(p.MessageType):

    def __init__(
        self,
        header: req_header_t = None,
        body: req_body_t = None,
    ) -> None:
        self.header = header
        self.body = body

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('header', req_header_t, 0),  # required
            2: ('body', req_body_t, 0),  # required
        }
