# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

from .command_t import command_t
from .error_t import error_t

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class res_body_t(p.MessageType):

    def __init__(
        self,
        command: command_t = None,
        parameter: bytes = None,
        error: error_t = None,
        has_more: bool = None,
    ) -> None:
        self.command = command
        self.parameter = parameter
        self.error = error
        self.has_more = has_more

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('command', command_t, 0),  # required
            2: ('parameter', p.BytesType, 0),
            3: ('error', error_t, 0),
            4: ('has_more', p.BoolType, 0),  # required
        }
