# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class set_label_req_parameter_t(p.MessageType):

    def __init__(
        self,
        label: str = None,
    ) -> None:
        self.label = label

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('label', p.UnicodeType, 0),  # required
        }
