# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class sync_account_info_req_parameter_t(p.MessageType):

    def __init__(
        self,
        total_num: int = None,
        account_idx: int = None,
        date: str = None,
        coin_group: str = None,
        coin_name: str = None,
        label: str = None,
        balance: str = None,
        address_path: str = None,
    ) -> None:
        self.total_num = total_num
        self.account_idx = account_idx
        self.date = date
        self.coin_group = coin_group
        self.coin_name = coin_name
        self.label = label
        self.balance = balance
        self.address_path = address_path

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('total_num', p.UVarintType, 0),  # required
            2: ('account_idx', p.UVarintType, 0),  # required
            3: ('date', p.UnicodeType, 0),  # required
            4: ('coin_group', p.UnicodeType, 0),  # required
            5: ('coin_name', p.UnicodeType, 0),  # required
            6: ('label', p.UnicodeType, 0),  # required
            7: ('balance', p.UnicodeType, 0),  # required
            8: ('address_path', p.UnicodeType, 0),  # required
        }
