# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

p2pkh = 0  # type: Literal[0]
p2pk = 1  # type: Literal[1]
p2sh = 2  # type: Literal[2]
multisig = 3  # type: Literal[3]
p2wpkh = 4  # type: Literal[4]
p2wsh = 5  # type: Literal[5]
change = 255  # type: Literal[255]
