# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class transaction_retrieve_res_parameter_t(p.MessageType):

    def __init__(
        self,
        tx_blk_idx: int = None,
        tx_blk: bytes = None,
    ) -> None:
        self.tx_blk_idx = tx_blk_idx
        self.tx_blk = tx_blk

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('tx_blk_idx', p.UVarintType, 0),  # required
            2: ('tx_blk', p.BytesType, 0),  # required
        }
