# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class transaction_update_script_req_parameter_t(p.MessageType):

    def __init__(
        self,
        input_idx: int = None,
        script: bytes = None,
    ) -> None:
        self.input_idx = input_idx
        self.script = script

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('input_idx', p.UVarintType, 0),  # required
            2: ('script', p.BytesType, 0),  # required
        }
