# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class transaction_finish_res_parameter_t(p.MessageType):

    def __init__(
        self,
        tx_size: int = None,
        tx_blk_size: int = None,
    ) -> None:
        self.tx_size = tx_size
        self.tx_blk_size = tx_blk_size

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('tx_size', p.UVarintType, 0),  # required
            2: ('tx_blk_size', p.UVarintType, 0),  # required
        }
