# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class txreq_message_sign_update_t(p.MessageType):

    def __init__(
        self,
        message_blk_idx: int = None,
        message_blk: bytes = None,
    ) -> None:
        self.message_blk_idx = message_blk_idx
        self.message_blk = message_blk

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('message_blk_idx', p.UVarintType, 0),  # required
            2: ('message_blk', p.BytesType, 0),  # required
        }
