# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class txreq_message_sign_parameter_t(p.MessageType):

    def __init__(
        self,
        key_path: str = None,
        total_msg_len: int = None,
        message_blk: bytes = None,
    ) -> None:
        self.key_path = key_path
        self.total_msg_len = total_msg_len
        self.message_blk = message_blk

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('key_path', p.UnicodeType, 0),  # required
            2: ('total_msg_len', p.UVarintType, 0),  # required
            3: ('message_blk', p.BytesType, 0),  # required
        }
