# Automatically generated by pb2py
# fmt: off
from .. import prototrez as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class txres_message_sign_t(p.MessageType):

    def __init__(
        self,
        address: str = None,
        msg_signed: bytes = None,
    ) -> None:
        self.address = address
        self.msg_signed = msg_signed

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('address', p.UnicodeType, 0),  # required
            2: ('msg_signed', p.BytesType, 0),  # required
        }
