# Automatically generated by pb2py
# fmt: off
if False:
    from typing_extensions import Literal

init = 0  # type: Literal[0]
ready = 1  # type: Literal[1]
secure = 2  # type: Literal[2]
locked_fp = 3  # type: Literal[3]
locked_pin = 4  # type: Literal[4]
invalid = 255  # type: Literal[255]
