name: Build sim
description: Build device simulator(s)
inputs:
  name:
    description: Device name from matrix (e.g. trezor-1, coldcard, jade)
    required: true
  archive:
    description: Archive base name (e.g. trezor-firmware)
    required: true
  paths:
    description: Space-separated paths to include in the archive
    required: true
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf libsdl2-image-dev libslirp-dev libpcsclite-dev ninja-build
        pip install poetry
        wget https://github.com/protocolbuffers/protobuf/releases/download/v22.0/protoc-22.0-linux-x86_64.zip
        sudo unzip protoc-22.0-linux-x86_64.zip -d /usr/local
        protoc --version

    - name: Build simulator
      shell: bash
      run: |
        set -euxo pipefail
        git config --global user.email 'ci@ci.com'
        git config --global user.name 'ci'
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        cd test
        ./setup_environment.sh --"${{ inputs.name }}"
        cd ..
        tar -czf "${{ inputs.archive }}.tar.gz" ${{ inputs.paths }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-sim
        path: ${{ inputs.archive }}.tar.gz

